// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6A2ZKpzMplRGekva3J3itRWCfyHRBRNk',
    appId: '1:128514143913:web:b82114a85453a7dd1b5bb8',
    messagingSenderId: '128514143913',
    projectId: 'new-crewin',
    authDomain: 'new-crewin.firebaseapp.com',
    storageBucket: 'new-crewin.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqhKIZ56sh321ED4qmqCB6jOIghhK5Bpg',
    appId: '1:128514143913:android:3cbe03cab415ced51b5bb8',
    messagingSenderId: '128514143913',
    projectId: 'new-crewin',
    storageBucket: 'new-crewin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEmB5IyqaHs2huf1iu3XPXwtqL7U7h5g',
    appId: '1:128514143913:ios:be85d4f32524e2a21b5bb8',
    messagingSenderId: '128514143913',
    projectId: 'new-crewin',
    storageBucket: 'new-crewin.appspot.com',
    iosClientId: '128514143913-qkvkn2ih9a2e5n837heouugipe186fq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrewin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEmB5IyqaHs2huf1iu3XPXwtqL7U7h5g',
    appId: '1:128514143913:ios:be85d4f32524e2a21b5bb8',
    messagingSenderId: '128514143913',
    projectId: 'new-crewin',
    storageBucket: 'new-crewin.appspot.com',
    iosClientId: '128514143913-qkvkn2ih9a2e5n837heouugipe186fq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.newCrewin',
  );
}
